# Generated by Django 5.2 on 2025-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('idea', models.TextField()),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
